#app.yaml
runtime: python39

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: whatdoyoumean?
  CLOUD_SQL_DATABASE_NAME: weight-workouts-database
  CLOUD_SQL_CONNECTION_NAME: weight-workouts:us-central1:weight-workouts-db